Remove secrets.ini from gitignore and fixture * fix debian ignored files list * fix test debian install * split test into functions

diff --git a/test/test_debian_install b/test/test_debian_install
--- a/test/test_debian_install
+++ b/test/test_debian_install
@@ -1,22 +1,45 @@
 #!/bin/bash
 
-while IFS=$'\n' read line; do
-  findargs+=('-not' '-path' "$line")
-done < "./debianIgnoredPaths"
+src_root="$(dirname "$PWD")"
 
-readarray filesPath < <(find . -type f "${findargs[@]}")
-readarray installedFilesPath < <(find /opt/kong -type f)
+mapIgnoredPathsIntoFindArgs() {
+  while IFS=$'\n' read line; do
+    findargs+=('-not' '-path' "$src_root/$line")
+  done < "./debianIgnoredPaths"
+}
 
-for filePath in ${filesPath[@]}; do
-  if [[ ! " ${installedFilesPath[@]} " =~ "/opt/kong/${filePath:2}" ]]; then
-    notInstalledFiles+=("* ${filePath:2}")
+mapSrcFilesIntoRelativePaths() {
+  appendRelativePath() {
+    filesPath+=(${2##"$(echo $src_root)"});
+  }
+  mapfile -c1 -C 'appendRelativePath' -t < <(find "$src_root/" -type f "${findargs[@]}");
+}
+
+listInstalledFiles() {
+  readarray installedFilesPath < <(find /opt/kong -type f)
+}
+
+assertInstalledVersusSourceFiles() {
+  for filePath in ${filesPath[@]}; do
+    if [[ ! " ${installedFilesPath[@]} " =~ "/opt/kong${filePath}" ]]; then
+      notInstalledFiles+=("${filePath:1}")
+    fi
+  done
+}
+
+showResultsAndExit() {
+  if [ ${#notInstalledFiles[@]} -ne 0 ]; then
+    echo -e "\nThe following files are missing from the debian install package file or need to be declared as ignored:\n"
+    printf '* %s\n' "${notInstalledFiles[@]}"
+    echo -e "\n"
+    exit 1
+  else
+    exit 0
   fi
-done
+}
 
-if [ ${#notInstalledFiles[@]} -ne 0 ]; then
-  echo "The following files are missing from the debian install package file or need to be declared as ignored:"
-  (IFS=$'\n'; echo "${notInstalledFiles[*]}")
-  exit 1
-else
-  exit 0
-fi
+mapIgnoredPathsIntoFindArgs
+mapSrcFilesIntoRelativePaths
+listInstalledFiles
+assertInstalledVersusSourceFiles
+showResultsAndExit
