Add control and debtool configs * toml to allow test to be ran in docker * Add control build dependency to docker * Add script to run testss smartly

diff --git a/tests b/tests
--- a/tests
+++ b/tests
@@ -1,3 +1,23 @@
 #!/bin/bash
-./test_plugin mtls_certs_manager
-./test_plugin client_consumer_validator
+result=0
+error_index=1
+
+assert_exit_code() {
+  ./$1
+  if [[ $? -ne 0 ]]; then
+      result=$(($result + $error_index))
+      echo "Failed running: $1"
+  fi
+  error_index=$(($error_index+1))
+}
+
+assert_exit_code "test_plugin mtls_certs_manager"
+assert_exit_code "test_plugin client_consumer_validator"
+
+if [[ $result -eq 0 ]]; then
+  echo "All tests RAN OK."
+else
+  echo "Some tests failed, exit code was: $? ..."
+fi
+
+exit $result
