Remove exit and call callback in postinst * Remove reloader script

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -9,17 +9,17 @@ nginx_path="/opt/kong/nginx"
 
 runPostInstChecksums() {
     echo -e "\nGenerating post-install checksums into file $2"
-    find $1 -print0 2>/dev/null -type f -exec sha1sum "{}" + > "$2"
+    find $1 -print0 2>/dev/null -type f -name $3 -exec sha1sum "{}" + > "$2"
 }
 
 assertIsInstalledAndExitIfNeeded() {
     which $1
-    if [[ $? -ne 0 ]]; then
-        echo -e "\n$1 isn't installed cannot restart $2"
-        current_time=$(date "+%Y.%m.%d-%H.%M.%S")
-        echo "$2 is pending to be restarted because it changed - $current_time" > "/opt/kong/$2-pending-restart.log"
-        exit 0
+    if [[ $? -eq 0 ]]; then
+        $3
     fi
+    echo -e "\n$1 isn't installed cannot restart $2"
+    current_time=$(date "+%Y.%m.%d-%H.%M.%S")
+    echo "$2 is pending to be restarted because it changed - $current_time" > "/opt/kong/$2-pending-restart.log"
 }
 
 restartKongIfNeeded() {
@@ -44,12 +44,11 @@ compareChecksumsAndRestartIfneeded() {
     else
         echo "$4 files were updated/installed, restarting $4"
         cd /opt/kong
-        assertIsInstalledAndExitIfNeeded "$3" "$4"
-        $5
+        assertIsInstalledAndExitIfNeeded "$3" "$4" $5
     fi
 }
 
-runPostInstChecksums "$plugins_path" "$post_inst_plugins_checksums"
-runPostInstChecksums "$nginx_path" "$post_inst_nginx_checksums"
-compareChecksumsAndRestartIfneeded "$post_inst_plugins_checksums" "$pre_inst_plugins_checksums" "docker-compose" "kong" restartKongIfNeeded
-compareChecksumsAndRestartIfneeded "$post_inst_nginx_checksums" "$pre_inst_nginx_checksums" "nginx" "nginx" restartNginxIfNeeded
+runPostInstChecksums $plugins_path $post_inst_plugins_checksums "*.lua"
+runPostInstChecksums $nginx_path $post_inst_nginx_checksums "*.conf"
+compareChecksumsAndRestartIfneeded $post_inst_nginx_checksums $pre_inst_nginx_checksums "nginx" "nginx" restartNginxIfNeeded
+compareChecksumsAndRestartIfneeded $post_inst_plugins_checksums $pre_inst_plugins_checksums "docker-compose" "kong" restartKongIfNeeded
