Add log in case docker-compose isn't available * Add more testing

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -4,24 +4,36 @@ runPostInstChecksums() {
     source /var/lib/dpkg/info/kong-docker-compose.preinst "postinst"
 }
 
-compareAndChecksumsAndRestartKongIfneeded() {
+assertDockerComposeIsInstalledAndExitIfNeeded() {
+    which docker-compose
+    if [[ $? -ne 0 ]]; then
+        echo -e "\ndocker-compose isn't installed cannot restart Kong"
+        current_time=$(date "+%Y.%m.%d-%H.%M.%S")
+        echo "KONG PENDING RESTART FOR PLUGINS RELOADING - $current_time" > /opt/kong/kong-pending-restart.log
+        exit 0
+    fi
+}
+
+restartKong() {
+    docker-compose restart kong
+}
+
+compareChecksumsAndRestartKongIfneeded() {
     if cmp --silent -- "$post_inst_checksums" "$pre_inst_checksums"; then
         echo "Previous plugin files are identical to the new ones, avoiding restart"
     else
         echo "Plugins were updated/installed, restarting kong"
         cd /opt/kong
-        which docker-compose
-        if [[ $? -ne 0 ]]; then
-            echo -e "\nDocker compose isn't installed cannot restart Kong"
-            exit 0
-        fi
-        docker-compose restart kong
+        assertDockerComposeIsInstalledAndExitIfNeeded
+        restartKong
     fi
 }
 
+showChecksumFilenames() {
+    echo "post-install checksums: $post_inst_checksums"
+    echo "pre-install checksums: $pre_inst_checksums"
+}
+
 runPostInstChecksums
-
-echo "post-install checksums: $post_inst_checksums"
-echo "pre-install checksums: $pre_inst_checksums"
-
-compareAndChecksumsAndRestartKongIfneeded
+showChecksumFilenames
+compareChecksumsAndRestartKongIfneeded
